import type { CTSInventoryItem, AvailabilityResponse } from '@/types/catalog';

export const FIXTURE_BRIDGIFY_EXPERIENCE: CTSInventoryItem = {
  id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
  supplier_slug: 'bridgify',
  supplier_raw_ref: 'bridgify-eiffel-summit',
  type: 'EXPERIENCE',
  title: 'Eiffel Tower Summit Access with Guide',
  description: 'Skip the line and reach the summit of the Eiffel Tower with a local guide.',
  latitude: 48.8584,
  longitude: 2.2945,
  city: 'Paris',
  country: 'France',
  timezone: 'Europe/Paris',
  category: 'sightseeing-tours',
  category_name: 'Sightseeing Tours',
  duration_minutes: 120,
  vehicle_class: null,
  star_rating: null,
  image_urls: ['https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=800'],
  amenities: null,
  meal_plans: null,
  route_origin: null,
  route_destination: null,
  price_from: 62.50,
  price_currency: 'EUR',
  rating: 4.7,
  review_count: 2341,
  raw_content: { provider: 'bridgify', original_id: 'eiffel-summit-123' },
  is_active: true,
  canonical_id: null,
  attraction_id: null,
  global_poi_id: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
  last_synced_at: '2026-04-15T10:30:00Z',
  created_at: '2026-03-01T00:00:00Z',
  updated_at: '2026-04-15T10:30:00Z',
};

export const FIXTURE_HOTELBEDS_HOTEL: CTSInventoryItem = {
  id: '6ba7b810-9dad-11d1-80b4-00c04fd430c8',
  supplier_slug: 'hotelbeds-hotels',
  supplier_raw_ref: '170950',
  type: 'HOTEL',
  title: 'Hotel & Spa La Belle Juliette',
  description: 'Boutique hotel in Saint-Germain-des-Prés with spa and garden terrace.',
  latitude: 48.8490,
  longitude: 2.3275,
  city: 'Paris',
  country: 'France',
  timezone: 'Europe/Paris',
  category: null,
  category_name: null,
  duration_minutes: null,
  vehicle_class: null,
  star_rating: 4,
  image_urls: ['17/170950/170950a_hb_ro_095.jpg', '17/170950/170950a_hb_ro_042.jpg'],
  amenities: ['WiFi', 'Spa', 'Room Service', 'Bar', 'Garden'],
  meal_plans: ['Room Only', 'Bed and Breakfast'],
  route_origin: null,
  route_destination: null,
  price_from: null,
  price_currency: 'EUR',
  rating: 4.2,
  review_count: 567,
  raw_content: {
    facilityGroups: [
      { facilityGroupCode: 10, facilities: [{ facilityCode: 70 }] },
      { facilityGroupCode: 60, facilities: [{ facilityCode: 261 }] },
    ],
  },
  is_active: true,
  canonical_id: null,
  attraction_id: null,
  global_poi_id: null,
  last_synced_at: '2026-04-10T12:00:00Z',
  created_at: '2026-03-15T00:00:00Z',
  updated_at: '2026-04-10T12:00:00Z',
};

export const FIXTURE_MINIMAL_ITEM: CTSInventoryItem = {
  id: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
  supplier_slug: 'hotelbeds-activities',
  supplier_raw_ref: 'ACT-99999',
  type: 'EXPERIENCE',
  title: 'Barcelona City Tour',
  description: null,
  latitude: null,
  longitude: null,
  city: 'Barcelona',
  country: null,
  timezone: null,
  category: null,
  category_name: null,
  duration_minutes: null,
  vehicle_class: null,
  star_rating: null,
  image_urls: null,
  amenities: null,
  meal_plans: null,
  route_origin: null,
  route_destination: null,
  price_from: null,
  price_currency: null,
  rating: null,
  review_count: null,
  raw_content: null,
  is_active: true,
  canonical_id: null,
  attraction_id: null,
  global_poi_id: null,
  last_synced_at: '2026-04-01T00:00:00Z',
  created_at: '2026-04-01T00:00:00Z',
  updated_at: '2026-04-01T00:00:00Z',
};

export const FIXTURE_DUFFEL_FLIGHT: CTSInventoryItem = {
  id: 'flight-duffel-ba-lhr-jfk',
  supplier_slug: 'duffel',
  supplier_raw_ref: 'off_00001',
  type: 'FLIGHT',
  title: 'British Airways LHR→JFK 2026-07-15',
  description: 'British Airways BA112 · Fare: Basic Economy',
  latitude: null,
  longitude: null,
  city: 'London',
  country: 'GB',
  timezone: null,
  category: 'Economy',
  category_name: null,
  duration_minutes: 435,
  vehicle_class: null,
  star_rating: null,
  image_urls: ['https://assets.duffel.com/img/airlines/for-light-background/full-color-lockup/BA.svg'],
  amenities: null,
  meal_plans: null,
  route_origin: 'LHR',
  route_destination: 'JFK',
  price_from: 325.00,
  price_currency: 'GBP',
  rating: null,
  review_count: null,
  raw_content: {
    offer_id: 'off_00001',
    origin: 'LHR',
    origin_city: 'London',
    destination: 'JFK',
    destination_city: 'New York',
    departing_at: '2026-07-15T10:30:00',
    arriving_at: '2026-07-15T14:45:00',
    duration: 'PT7H15M',
    carrier_name: 'British Airways',
    carrier_iata: 'BA',
    flight_number: 'BA112',
    fare_brand: 'Basic Economy',
    cabin_class: 'economy',
    total_amount: '325.00',
    total_currency: 'GBP',
    stops: 0,
    conditions: { refund_before_departure: { allowed: false } },
    expires_at: '2026-07-15T12:00:00Z',
  },
  is_active: true,
  canonical_id: null,
  attraction_id: null,
  global_poi_id: null,
  last_synced_at: '2026-05-12T08:00:00Z',
  created_at: '2026-05-12T00:00:00Z',
  updated_at: '2026-05-12T08:00:00Z',
};

export const FIXTURE_HOTEL_AVAILABILITY: AvailabilityResponse = {
  ok: true,
  supplier: 'hotelbeds-hotels',
  step: 'availability',
  latency_ms: 1200,
  data: {
    rooms: [
      {
        code: 'DBL.ST',
        name: 'Double Standard',
        rates: [
          {
            rateKey: 'RATE-KEY-EXPIRES-IN-10-MIN|20260715|20260718|DBL.ST|NRF',
            net: 450.00,
            currency: 'EUR',
            cancellationPolicies: [
              { from: '2026-07-13T23:59:00+02:00', amount: '450.00' },
            ],
            boardName: 'Room Only',
          },
          {
            rateKey: 'RATE-KEY-EXPIRES-IN-10-MIN|20260715|20260718|DBL.ST|BB',
            net: 520.00,
            currency: 'EUR',
            cancellationPolicies: [
              { from: '2026-07-14T23:59:00+02:00', amount: '520.00' },
            ],
            boardName: 'Bed and Breakfast',
          },
        ],
      },
    ],
  },
};

export const FIXTURE_BROWSE_RESPONSE = {
  results: [FIXTURE_BRIDGIFY_EXPERIENCE, FIXTURE_HOTELBEDS_HOTEL, FIXTURE_MINIMAL_ITEM],
  total: 3,
  page: 1,
  pages: 1,
  limit: 20,
};

export const FIXTURE_EMPTY_RESPONSE = {
  results: [],
  total: 0,
  page: 1,
  pages: 0,
  limit: 20,
};
